#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPArrowHeadProperties
@end

@interface ASPArrowHeadProperties : ASPObject


@property(nonatomic) NSString* length;

@property(nonatomic) NSString* style;

@property(nonatomic) NSString* width;

@end
