#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPPdfExportOptions
@end

@interface ASPPdfExportOptions : ASPObject


@property(nonatomic) NSString* textCompression;

@property(nonatomic) NSNumber* embedFullFonts;

@property(nonatomic) NSString* compliance;

@property(nonatomic) NSString* jpegQuality;

@property(nonatomic) NSNumber* saveMetafilesAsPng;

@property(nonatomic) NSString* password;

@property(nonatomic) NSNumber* embedTrueTypeFontsForASCII;

@property(nonatomic) NSString* exportFormat;

@end
