#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPSlideComment
@end

@interface ASPSlideComment : ASPObject


@property(nonatomic) NSString* author;

@property(nonatomic) NSString* text;

@property(nonatomic) NSString* createdTime;

@end
