#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLineFormat.h"
#import "ASPResourceUriElement.h"
#import "ASPFillFormat.h"
#import "ASPResourceUri.h"


@protocol ASPShape
@end

@interface ASPShape : ASPObject


@property(nonatomic) NSString* text;

@property(nonatomic) ASPResourceUriElement* paragraphs;

@property(nonatomic) NSString* shapeType;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSString* alternativeText;

@property(nonatomic) NSNumber* hidden;

@property(nonatomic) NSNumber* X;

@property(nonatomic) NSNumber* Y;

@property(nonatomic) NSNumber* zOrderPosition;

@property(nonatomic) ASPResourceUriElement* shapes;

@property(nonatomic) ASPFillFormat* fillFormat;

@property(nonatomic) ASPLineFormat* lineFormat;

@property(nonatomic) ASPResourceUri* selfUri;

@property(nonatomic) NSArray<ASPResourceUri>* alternateLinks;

@property(nonatomic) NSArray<ASPResourceUri>* links;

@end
