#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPTiffExportOptions
@end

@interface ASPTiffExportOptions : ASPObject


@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSNumber* dpiX;

@property(nonatomic) NSNumber* dpiY;

@property(nonatomic) NSString* compression;

@property(nonatomic) NSString* exportFormat;

@end
