#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPCustomDashPattern
@end

@interface ASPCustomDashPattern : ASPObject


@property(nonatomic) NSArray* /* NSNumber */ items;

@end
