#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPResourceUriElement.h"
#import "ASPResourceUri.h"


@protocol ASPDocument
@end

@interface ASPDocument : ASPObject


@property(nonatomic) ASPResourceUriElement* documentProperties;

@property(nonatomic) ASPResourceUriElement* slides;

@property(nonatomic) ASPResourceUriElement* images;

@property(nonatomic) ASPResourceUri* selfUri;

@property(nonatomic) NSArray<ASPResourceUri>* alternateLinks;

@property(nonatomic) NSArray<ASPResourceUri>* links;

@end
