#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPResourceUri.h"


@protocol ASPFormatScheme
@end

@interface ASPFormatScheme : ASPObject


@property(nonatomic) NSArray<ASPResourceUri>* backgroundStyles;

@property(nonatomic) NSArray<ASPResourceUri>* effectStyles;

@property(nonatomic) NSArray<ASPResourceUri>* fillStyles;

@property(nonatomic) NSArray<ASPResourceUri>* lineStyles;

@property(nonatomic) ASPResourceUri* selfUri;

@property(nonatomic) NSArray<ASPResourceUri>* alternateLinks;

@property(nonatomic) NSArray<ASPResourceUri>* links;

@end
