#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPFontSet.h"
#import "ASPResourceUri.h"


@protocol ASPFontScheme
@end

@interface ASPFontScheme : ASPObject


@property(nonatomic) ASPFontSet* major;

@property(nonatomic) ASPFontSet* minor;

@property(nonatomic) NSString* name;

@property(nonatomic) ASPResourceUri* selfUri;

@property(nonatomic) NSArray<ASPResourceUri>* alternateLinks;

@property(nonatomic) NSArray<ASPResourceUri>* links;

@end
