#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPHtmlExportOptions
@end

@interface ASPHtmlExportOptions : ASPObject


@property(nonatomic) NSNumber* saveAsZip;

@property(nonatomic) NSString* subDirectoryName;

@property(nonatomic) NSString* exportFormat;

@end
