#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPArrowHeadProperties.h"
#import "ASPFillFormat.h"
#import "ASPCustomDashPattern.h"


@protocol ASPLineFormat
@end

@interface ASPLineFormat : ASPObject


@property(nonatomic) NSString* alignment;

@property(nonatomic) NSString* capStyle;

@property(nonatomic) NSString* dashStyle;

@property(nonatomic) NSString* joinStyle;

@property(nonatomic) NSString* style;

@property(nonatomic) ASPArrowHeadProperties* beginArrowHead;

@property(nonatomic) ASPArrowHeadProperties* endArrowHead;

@property(nonatomic) ASPCustomDashPattern* customDashPattern;

@property(nonatomic) ASPFillFormat* fillFormat;

@property(nonatomic) NSNumber* miterLimit;

@property(nonatomic) NSNumber* width;

@end
