#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPResourceUri
@end

@interface ASPResourceUri : ASPObject


@property(nonatomic) NSString* href;

@property(nonatomic) NSString* relation;

@property(nonatomic) NSString* linkType;

@property(nonatomic) NSString* title;

@end
