#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPFillFormat.h"
#import "ASPResourceUri.h"


@protocol ASPSlideBackground
@end

@interface ASPSlideBackground : ASPObject


@property(nonatomic) NSString* type;

@property(nonatomic) ASPFillFormat* fillFormat;

@property(nonatomic) ASPResourceUri* selfUri;

@property(nonatomic) NSArray<ASPResourceUri>* alternateLinks;

@property(nonatomic) NSArray<ASPResourceUri>* links;

@end
